# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7f9958df65d52bd537124ce3f609f0d5593fecd90f9d41a4aa1580905f922df674e0b0b1ec3980c5a39593b82f64989211298153e944a6ff4b9f76998a31d15

test:
  secret_key_base: 9d5efcf42f4c5efa92cecc835a5c8e9604cdf6b6742492956d55be3392ec3e702645f5c219bebfc94abf346bb4902c56846f33980518d69c477211f91ecb35fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
